<a href="https://colab.research.google.com/github/perfectporfoliopablo/Curso-Lenguaje-Orientado-a-objetos-y-bases-de-datos/blob/main/NUMPY_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u>**INTRODUCCIÓN A NUMPY**</u>

NumPy es una biblioteca de Python que proporciona soporte para crear *vectores* y *matrices* grandes multidimensionales (arrays), junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas. Es una herramienta esencial para la computación científica y el análisis de datos en Python.

Las principales características de NumPy son:

* **Arreglos multidimensionales:** NumPy proporciona un tipo de datos de arreglo multidimensional llamado `ndarray`. Los `ndarray` son objetos eficientes y flexibles que pueden almacenar datos de cualquier tipo.
* **Operaciones matemáticas:** NumPy proporciona una gran colección de funciones matemáticas de alto nivel para operar con arreglos. Estas funciones incluyen operaciones básicas como suma, resta, multiplicación y división, así como operaciones más complejas como álgebra lineal y estadística.
* **Funciones de utilidad:** NumPy también proporciona una variedad de funciones de utilidad para manipular arreglos, como funciones para leer y escribir datos de archivos, funciones para generar arreglos aleatorios y funciones para realizar operaciones de búsqueda y clasificación.

NumPy es una biblioteca muy popular y utilizada en una amplia gama de aplicaciones científicas y de ingeniería. Es una herramienta esencial para cualquier persona que quiera realizar cálculos numéricos o análisis de datos en Python.

Aquí hay algunos ejemplos de cómo se puede usar NumPy:

* **Para realizar cálculos matemáticos:** NumPy se puede usar para realizar cálculos matemáticos básicos, como suma, resta, multiplicación y división. También se puede usar para realizar operaciones más complejas, como álgebra lineal y estadística.
* **Para analizar datos:** NumPy se puede usar para analizar datos de una variedad de fuentes, como archivos de texto, bases de datos y sensores. Se puede usar para realizar tareas como limpieza de datos, visualización de datos y aprendizaje automático.
* **Para crear simulaciones:** NumPy se puede usar para crear simulaciones de sistemas físicos o biológicos. Se puede usar para modelar el comportamiento de sistemas complejos, como el clima o el mercado de valores.

Mas info en [Numpy](https://numpy.org/doc/stable/reference/index.html#reference).

In [ ]:
# Importamos la librería de Numpy

import numpy as np



## <u>***1.- Arrays Básicos***</u>


Para crear un array básico usaremos el método `array()` de Numpy.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array).

In [ ]:
a = np.array([1,2,3])

a

array([1, 2, 3])

Podemos crear un array relleno de ceros (0) usando el método `zeros()`.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros).

In [ ]:
a=np.zeros(3)

a

array([0., 0., 0.])

Y también podemos crear un array relleno de unos (1), usando el método `ones()`.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones).

In [ ]:
a=np.ones(4)

a

array([1., 1., 1., 1.])

Otra posibilidad es crear un array con elementos aleatorios, usando el método `rand()` de la clase `Numpy.Random()` .

Los parámetros que admite este método son tantos como dimensiones quieres que tenga el array.

En el ejemplo del snippet siguiente `rand(4,3)`, definimos un array bidimensional; un array que contiene 4 arrays con 3 elemento en cada array.

Más info en [Numpy](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html#numpy.random.rand).

In [ ]:
a=np.random.rand(4,3)


a

array([[0.49393868, 0.60086662, 0.02326413],
       [0.85281676, 0.0859833 , 0.09121302],
       [0.17951771, 0.85046559, 0.43762992],
       [0.78633798, 0.80457485, 0.85185392]])

La función `empty()` en **NumPy** se utiliza para crear un nuevo arreglo (array) multidimensional sin asignar ningún valor inicial a sus elementos.

La función `empty()` reserva espacio en la memoria para el array, pero no inicializa los valores de sus elementos.

Un ejemplo práctico de uso de empty sería cuando se necesita crear un array con dimensiones específicas, pero los valores iniciales no son relevantes en ese momento y se van a sobrescribir más adelante en el código.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.empty.html#numpy.empty).

In [ ]:
aa=np.empty((3, 4))

aa

array([[0.49393868, 0.60086662, 0.02326413, 0.85281676],
       [0.0859833 , 0.09121302, 0.17951771, 0.85046559],
       [0.43762992, 0.78633798, 0.80457485, 0.85185392]])

In [ ]:
# Otro ejemplo de empty().

arr=np.empty(5)

arr

array([5.01835890e-310, 0.00000000e+000, 2.37663529e-312, 2.56761491e-312,
       2.37151510e-322])

Podemos crear un array con una rango de elementos numéricos, utilizando el método `arange()` (funciona igual que la función `range()` de Python y admite los mismos parámetros).

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy.arange).

In [ ]:
a=np.arange(5)

a

array([0, 1, 2, 3, 4])

En este ejemplo, creamos un array con un rango de intervalos consecutivos:
+   El primer parámetro (2), es el número de inicio del intervalo (incluido).
+   El segundo parámetro (16), es el número de fin del intervalo (excluido).

In [ ]:
a=np.arange(2, 16)

a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

En el siguiente snippet, le añadimos un salto de 6 añadiendo el tercer parámetro.

In [ ]:
a=np.arange(0, 17, 6)

a

array([ 0,  6, 12])

El método `linspace()` devuelve números espaciados uniformemente sobre un intervalo especificado.

+   El primer argumento es el número de inicio del intervalo (incluido).
+   El segundo argumento es el número de fin del intervalo (incluido por defecto).
+   El tercer argumento es el número de muestras (elementos) a generar.

In [ ]:
a=np.linspace(0, 17, 8)

a

array([ 0.        ,  2.42857143,  4.85714286,  7.28571429,  9.71428571,
       12.14285714, 14.57142857, 17.        ])

Podemos especificar el tipo de dato que tendrá el intervalo con el parámetro `dtype=` (por defecto es `float` ).

In [ ]:
a= np.linspace(0, 17, 25, dtype=int)

a

array([ 0,  0,  1,  2,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9,  9, 10, 11,
       12, 12, 13, 14, 14, 15, 16, 17])

In [ ]:
a=np.linspace(0, 17, 25).round(4)
a

array([ 0.    ,  0.7083,  1.4167,  2.125 ,  2.8333,  3.5417,  4.25  ,
        4.9583,  5.6667,  6.375 ,  7.0833,  7.7917,  8.5   ,  9.2083,
        9.9167, 10.625 , 11.3333, 12.0417, 12.75  , 13.4583, 14.1667,
       14.875 , 15.5833, 16.2917, 17.    ])

## <u>***2.- Ordenar, Quitar y Añadir Elementos en un Array***</u>

La funcion `sort()` devuelve una copia ordenada de un array que le pasemos como argumento.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort).

In [ ]:
a= np.array([2, 1, 5, 3, 7, 4, 6, 8])

a.sort()
a

array([1, 2, 3, 4, 5, 6, 7, 8])

También podemos ordenar un array en orden descendente usando la notación de índices (`[::-1]`) después del método `sort()`.

Camo ya sabemos en esta notación inidicamos que queremos todo el rango completo del array, con un salto de -1, es decir, del último al primero.

Por tanto, primero se ejecuta el método `sort()` y luego se devuelve el array invertido gracias a la notación de índices.

In [ ]:
a=np.array([2, 1, 5, 3, 7, 4, 6, 8])

np.sort(a)[::-1]



array([8, 7, 6, 5, 4, 3, 2, 1])

Si queremos ordenar una array multidimensional a lo largo del eje 0 (columnas), usaremos el parámetro `axis=0`.

El parámetro `axis=` admite tres valores:
+   `0` para ordenar los arrays multidimensionales por columnas.
+   `1` para ordenar los arrays multidimensionales por filas, es decir, ordenando los elementos de cada array interno.
+   `-1` (valor por defecto) para ordenar los arrays multidimensionales a lo largo del último eje. Suele tener el mismo efecto que ordenar por filas `(axis=1)`.

In [ ]:
# Mostramos el array sin ordenar.

a=np.array([[5, 2, 8], [1, 3, 6]])

a

array([[5, 2, 8],
       [1, 3, 6]])

In [ ]:
# Mostramos el array ordenado por columnas.

np.sort(a, axis=0)

array([[1, 2, 6],
       [5, 3, 8]])

In [ ]:
# Mostramos el array ordenado por filas.

a=np.array([[5, 2, 8], [1, 3, 6]])

np.sort(a, axis=1)

array([[2, 5, 8],
       [1, 3, 6]])

In [ ]:
# Para ordenarlos en descendente por filas podemos hacerlo asi:

a=np.array([[5, 2, 8], [1, 3, 6]])

np.sort(a, axis=1)[:, :: -1]

array([[8, 5, 2],
       [6, 3, 1]])

El método `concatenate()` nos permite concatenar arrays a lo largo de un eje.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate).

In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c= np.concatenate((a,b))

c

array([1, 2, 3, 4, 5, 6, 7, 8])

Otro ejemplo de concatenado pero ahora multidimensional, que podemos ver en el siguiente snippet, y usando el parámetro `axis=0` para unirlo por el eje de las columnas (eje por defecto):

In [ ]:
x=np.array([[1, 2], [3, 4]])
y=np.array([[5, 6], [7, 8]])

z=np.concatenate((x,y), axis=0)

z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Ahora, en vez de usar el `axis=0`, vamos a usar, esta vez, el `axis=1` (filas).

In [ ]:
x=np.array([[1, 2], [3, 4]])
y=np.array([[5, 6], [7, 8]])

z=np.concatenate((x,y), axis=1)

z


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Para eliminar elementos de un array usamos el metodo `delete()`.

> El método `delete()` usa 3 argumentos:
+   el array de entrada.
+   los indices de los elementos a eliminar.
+   el eje (opcional) a lo largo del cual se hace la eliminacion.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.delete.html#numpy.delete).

In [ ]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

np.delete(a, [1, 3, 4])  # Elimina el segundo y cuarto elemento del array

array([1, 3, 6, 7, 8, 9])

In [ ]:
np.delete(a, 1)

array([1, 3, 4, 5])

Si el array es multimensional debemos especificar el **eje** a lo largo del cual eliminamos los elementos.

In [ ]:
a=np.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

np.delete(a, 2, axis=1)  # Elimina la segunda columna del array

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
# Otro ejemplo:

a=np.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

np.delete(a, 1, axis=0)  # Elimina la segunda fila del array.

array([[1, 2, 3],
       [7, 8, 9]])

Para añadir elementos a un array podemos usar el metodo `append()`.

> El método `append()` usa 3 argumentos:
+   el array de entrada.
+   los elementos a añadir.
+   el eje a lo largo del cual se añaden.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.append.html#numpy.append).

In [ ]:
a= np.array([1, 2, 3])

np.append(a, [4, 5])



array([1, 2, 3, 4, 5])

De nuevo, para arrays multidimensionales debemos especificar el **eje** a lo largo del cual se añadirán los elementos nuevos.

In [ ]:
a= np.array([[1, 2, 3],
             [4, 5, 6]])

np.append(a, [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Si deseamos añadir nuevos elementos a un array de Numpy en una posicion especifica debemos usar el metodo `insert()`.

> El método `ìnsert()` necesita 3 argumentos:
+   el array de entrada.
+   el indice de la posicion de insercion.
+   los elementos a añadir.

In [ ]:
a= np.array([1, 2, 3, 4, 5])

np.insert(a, 4, 33) # Inserta el numero 33 en la posicion 4 del array.

array([ 1,  2,  3,  4, 33,  5])

In [ ]:
np.insert(a, -1, 33)

array([ 1,  2,  3,  4, 33,  5])

También podemos insertar elementos nuevos en arrays multidimensionales de forma parecida a los ejercicios anteriores.

In [ ]:
a= np.array([[1, 2, 3],
             [4, 5, 6]])

np.insert(a, 1, [0, 0], axis=1)  # Esta vez no me pide doble corchete como en el
                                 # ejercicio de antes, porque vamos a incluir
                                 # los elementos en los arrays ya existentes.



array([[1, 0, 2, 3],
       [4, 0, 5, 6]])

## <u>***3.- Como Saber la Forma, Tamaño y Dimensión de un Array***</u>

En esta sección vamos a usar tres propiedades de la clase `ndarray`, que como ya comentamos es una clase que maneja arrays multidimensionales:
+   La propiedad `.ndim`, que nos devuelve el número de dimensiones de un array. Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ndim.html#).
+   La propiedad `.size`, que nos devuelve el número de elementos de un array. Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html).
+   La propiedad `.shape`, nos devuelve una tupla con las dimensiones del array. Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html).

In [ ]:
# Para saber las dimensiones de un array( numero de ejes o dimensiones
# que tiene el array)

a=np.array([1, 2, 3])

a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
# Otro ejemplo:

a=np.array([[1, 2, 3], [4, 5, 6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a.size

6

In [ ]:
a.shape

(2, 3)

In [ ]:
# Otro ejemplo más:

a=np.array([[[0, 1, 2, 3],
             [4, 5, 6, 7]],

           [[0, 1, 2, 3],
            [4, 5, 6, 7]],

           [[0, 1, 2, 3],
            [4, 5, 6, 7]]])

a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
a.ndim

3

In [ ]:
a.size

24

In [ ]:
a.shape

(3, 2, 4)

Para saber el número total de elementos de un array usamos la propiedad `size`.

In [ ]:
a= np.array([1, 2, 3, 4, 5, 6])
a.size

6

La diferencia entre las propiedades `ndim` y `shape` es que `ndim` muestra un entero que representa la cantidad de dimensiones del array y `shape` devuelve una tupla que especifica la longitud de cada dimension del array.

In [ ]:
# Un ejemplo con la propiedad shape.

a= np.array([1, 2, 3, 4, 5])

a

array([1, 2, 3, 4, 5])

In [ ]:
a.shape

(5,)

In [ ]:
# Otro ejemplo con la propiedad shape.

a=np.array([[1, 2, 3, 3], [4, 5, 6, 6]])

a

array([[1, 2, 3, 3],
       [4, 5, 6, 6]])

In [ ]:
a.shape

(2, 4)

In [ ]:
# Y otro ejemplo más con la propiedad shape.

a=np.array([[[1, 2, 3, 3], [4, 5, 6, 6]],[[7, 8, 9, 9], [10, 11, 12, 12]]])

a

array([[[ 1,  2,  3,  3],
        [ 4,  5,  6,  6]],

       [[ 7,  8,  9,  9],
        [10, 11, 12, 12]]])

In [ ]:
a.shape

(2, 2, 4)

## <u>***4.- Remodelar (Reshape) un Array***</u>

Usando el método `arange()`, que vimos en la sección 1, creamos un nuevo array con 9 elementos (`0` a `8`), en el siguiente snippet:

In [ ]:
a = np.arange(9)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Y ahora remodelamos (reshape) el array anterior con el método `reshape()`.

> El método `reshape()` da una nueva forma a una matriz sin cambiar sus datos.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape).

In [ ]:
b = a.reshape(3,3)

b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

El mètodo `reshape()` se usa para cambiar la forma de un array multidimensional sin modificar sus datos subyacentes. La nueva forma debe ser compatible con la cantidad total de elementos del array original.

*   También sirve para preparar datos para el análisis:
    -   En el procesamiento de datos, es común tener que reformatear los datos para que se ajusten a un determinado modelo o algoritmo.

*   Y también se usa para trabajar con imágenes:
    -   En el caso de imágenes, es común representarlas como arreglos multidimensionales. Por ejemplo, una imagen en escala de grises puede ser representada como una matriz 2D, mientras que una imagen en color puede ser representada como una matriz 3D.

In [ ]:
# Creamos un array unidimensional de 12 elementos.

a= np.arange(12)

a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.shape

(12,)

In [ ]:
# En este snippet cambiamos la matriz a otra 3x4 (o también podría ser de 2x6).
b= a.reshape(3,4)

b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Un array de tres dimensiones sería:

`3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])`

In [ ]:
# En este snippet vamos a crear un array de 72 elementos, que en el siguiente
# snippet remodelaremos a uno de 4 dimensiones.

d = np.arange(72)

d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71])

El siguiente código remodela el array anterior con 4 arrays principales, que contienen 3 subarrays y cada uno de éstos contiene 2 subarrays con 3 elementos en cada array.

In [ ]:
c = np.reshape(d, (4,3,2,3))

c

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])



---


A continuación, vamos a ver cómo modificar las dimensiones de un array, utilizando una constante especial de **Numpy** llamada `newaxis`.

> La constante `newaxis` se usa para agregar una nueva dimensión a un array. Se puede usar de varias maneras, pero su uso más común es para permitir que **NumPy** realice operaciones de difusión, es decir, una operación que se realiza en todos los elementos de un array.

Más info en [Numpy](https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis).

In [ ]:
# En este ejemplo vamos a convertir un array de 1D en otro de 2D.

a=np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [ ]:
# Usamos newaxis para añadir un nuevo eje (axis) al principio del nuevo array.

a2=a[np.newaxis, :]

print(a2.shape)

print(a2)

(1, 6)
[[1 2 3 4 5 6]]


También puedes expandir la forma de un array insertando un nuevo eje (axis) en una posicion especifica, por ejemplo, en la posicion 1, usando el método `expand_dims()`.

> Este método expande la forma de un array y admite dos parámetros:
+   El array de entrada o array a expandir.
+   Posición donde se coloca el nuevo eje, usando el parámetro `axis=`.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html#numpy-expand-dims).

In [ ]:
# Creamos el nuevo array a expandir.

a=np.array([1, 2, 3, 4, 5, 6])

a.shape

(6,)

In [ ]:
# Expandimos la forma del array anterior en la posicion 1.

b=np.expand_dims(a, axis=1)

b.shape

(6, 1)

In [ ]:
# Volvemos a expandir el array anterior, pero esta vez, a la posicion 0.

c=np.expand_dims(a, axis=0)
c.shape

(1, 6)

## <u>***5.- Indexing and Slicing***</u>

El indexado (indexing) y el troceado (slicing) de arrays de Numpy, es muy parecido al que hacemos en Python con las listas.

In [ ]:
import numpy as np

# Creamos un nuevo array y mostramos el elemento que está en el índice 1.

data= np.array([1, 2, 3, 4, 5])

data[1]

2

In [ ]:
data[-2]

4

In [ ]:
# Mostramos los elementos del array desde el índice 1 (inclusive) al
# índice 4 (exclusivo).

data[1:4]

array([2, 3, 4])

In [ ]:
# Mostramos los elementos del array desde el índice 3 (inclusive)
# hasta el último elemento del array.

data[3:]

array([4, 5])

In [ ]:
data[:3]

array([1, 2, 3])

In [ ]:
data[::]

array([1, 2, 3, 4, 5])

In [ ]:
data[:]

array([1, 2, 3, 4, 5])

In [ ]:
# Mostramos los elementos del array desde el índice 4 (empezando desde
# el último) hasta el último elemento del array.

data[-4:]

array([2, 3, 4, 5])

In [ ]:
data[:-4]

array([1])

In [ ]:
# Podemos mostrar los valores del array que son menores a 5.
# Primero creamos un nuevo array bidimensional.

a= np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[::2, ::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a[::2,(1,3)]

array([[ 2,  4],
       [10, 12]])

In [ ]:
a[::2, 1::2]

array([[ 2,  4],
       [10, 12]])

In [ ]:
data=np.arange(0, 96).reshape(2,4,3,4)
data

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]],


       [[[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59]],

        [[60, 61, 62, 63],
         [64, 65, 66, 67],
         [68, 69, 70, 71]],

        [[72, 73, 74, 75],
         [76, 77, 78, 79],
         [80, 81, 82, 83]],

        [[84, 85, 86, 87],
         [88, 89, 90, 91],
         [92, 93, 94, 95]]]])

In [ ]:
data[1, 0, ::-1]

array([15, 14, 13, 12])

In [ ]:
data[1, [0,1], [0,2], 2]

array([50, 70])

In [ ]:
data[1, [0,0,1,1], [0,0,2,2], [0,2,0,2]]

array([48, 50, 68, 70])

In [ ]:
# Con este formato, nos muestra booleanos un array de booleanos
# con los resultados de la condición en cada elemento.

print(a<=5)

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


In [ ]:
# Usando la condición como índice nos dará, en esta ocasión, un array
# con los elementos que coinciden con la condición dada.

a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [ ]:
# O podemos mostrar los numeros iguales o mayores que 5

cinco= (a>=5)
a[cinco]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# O también podemos mostrar los elementos del array que son divisibles por 2.

divisible= a[a%2==0]
divisible

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
divisible=a[(a%2==0) & (a>7)]
divisible

array([ 8, 10, 12])

In [ ]:
divisible = a[(a%2==0) | (a>7)]
divisible

array([ 2,  4,  6,  8,  9, 10, 11, 12])

In [ ]:
# O los elementos del array que sean impares.

divisible= a[a%2!=0]

divisible

array([ 1,  3,  5,  7,  9, 11])

También es posible usar los operadores lógicos (`and` - `&`) y (`or` - `|`), para evaluar más de una condición.

In [ ]:
c= a[(a>2) & (a<11)]

c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
c=(a>5) | (a==5)

a[c]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

## <u>***6.- Como Crear un Array de Otro Array ya Existente***</u>

Para crear un array a partir de otro ya creado, solo hay que usar la notación de índices para trocear la parte del array que nos interesa y guardarlo en otra variable.

In [ ]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr1= a[3:8:2]

arr1

array([4, 6, 8])

También puedes apilar varios arrays verticalmente u horizontalmente, usando los métodos `vstack()` y `hstack()`.

> El método `vstack()` apila matrices en secuencia verticalmente (por filas). Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html#numpy.vstack).
>
> El método `hstack()` apila matrices en secuencia horizontalmente (por columnas). Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html).

In [ ]:
a1= np.array([[1, 1],
             [2, 2]])

a2= np.array([[3, 3],
              [4, 4]])

In [ ]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.vstack((a2, a1))

array([[3, 3],
       [4, 4],
       [1, 1],
       [2, 2]])

In [ ]:
np.concatenate((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

También puedes dividirlos en varios arrays mas pequeños, especificando
el número de arrays iguales, usando el método `hsplit()`.

Elmétodo `hsplit()` divide una matriz en varias submatrices horizontalmente (por columnas).

In [ ]:
# Creamos un array de 48 elementos, remodelado a un array bidimensional de
# 4 subarrays de 12 elementos cada uno.

x= np.arange(1, 49).reshape(4, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])

In [ ]:
# Y ahora dividimos la matriz en 3 submatrices por columnas lo que nos da un
# total de 4 subarrays de 4 elementos cada una.

np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16],
        [25, 26, 27, 28],
        [37, 38, 39, 40]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20],
        [29, 30, 31, 32],
        [41, 42, 43, 44]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24],
        [33, 34, 35, 36],
        [45, 46, 47, 48]])]

In [ ]:
np.vsplit(x,4)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]]),
 array([[37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])]

In [ ]:
np.vsplit(x, 4)[1]

array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x, 3)[0]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16],
       [25, 26, 27, 28],
       [37, 38, 39, 40]])

In [ ]:
# Otro ejemplo:

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Dividimos el array horizontalmente en dos partes
result = np.hsplit(arr, 2)

# Imprimimos los resultados
print("Array original:")
print(arr)

print("\nResultado de hsplit():")
print(result)

Array original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Resultado de hsplit():
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [ ]:
# Si quieres separarlo despues de la tercera y cuarta columna

np.hsplit(x, (3, 5))

[array([[ 1,  2,  3],
        [13, 14, 15],
        [25, 26, 27],
        [37, 38, 39]]),
 array([[ 4,  5],
        [16, 17],
        [28, 29],
        [40, 41]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34, 35, 36],
        [42, 43, 44, 45, 46, 47, 48]])]

In [ ]:
np.hsplit(x, (0,7))

[array([], shape=(4, 0), dtype=int64),
 array([[ 1,  2,  3,  4,  5,  6,  7],
        [13, 14, 15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29, 30, 31],
        [37, 38, 39, 40, 41, 42, 43]]),
 array([[ 8,  9, 10, 11, 12],
        [20, 21, 22, 23, 24],
        [32, 33, 34, 35, 36],
        [44, 45, 46, 47, 48]])]

## <u>***7.- Operaciones Básicas con Arrays***</u>

### 7.1.- Suma de Arrays

In [ ]:
# Creamos el primer array.

arr1= np.array([1, 2])

arr1

array([1, 2])

In [ ]:
# Creamos el segundo array de unos (1).

arr2= np.ones(2, dtype=int)
arr2

array([1, 1])

In [ ]:
# Realizamos la operación de suma de ambos arrays.

arr1+arr2

array([2, 3])

### 7.2.- Resta de Arrays

In [ ]:
# Realizamos la operación de resta de ambos arrays anteriores.

arr1 - arr2

array([0, 1])

### 7.3.- Multiplicación de Arrays

In [ ]:
# Realizamos la operación de multiplicación de ambos arrays anteriores.

arr1 * arr2

array([1, 2])

### 7.4.- División de Arrays

In [ ]:
# Realizamos la operación de división de ambos arrays anteriores.

arr2 / arr1

array([1. , 0.5])

### 7.5- Operaciones con los elementos de un array o matriz

In [ ]:
# Para sumar los elementos de un array

a= np.array([1, 2, 3, 4])

a.sum()

10

In [ ]:
# Para sumar las columnas en un array 2D debemos especificar el eje (axis).
# Creamos el array 2D:

b= np.array([[1, 1], [2, 2]])

b

array([[1, 1],
       [2, 2]])

In [ ]:
# Sumamos sobre el eje de columnas:

b.sum(axis=0)

array([3, 3])

In [ ]:
# Sumamos sobre el eje de filas:
b.sum(axis=1)

array([2, 4])

In [ ]:
# También podemos multiplicar un array por un número (se llama broadcast
# en ingles)

data= np.array([1.0, 2.0, 3.0, 4.0, 5.0])

data*1.6

array([1.6, 3.2, 4.8, 6.4, 8. ])

In [ ]:
# Obtener el elemento con el valor máximo.

data.max()

5.0

In [ ]:
# Obtener el elemento con el valor mínimo.

data.min()

1.0

In [ ]:
# Obtener la media de todos los elementos del array.

data.mean()

3.0

In [ ]:
# Para multiplicar todos los elementos entre ellos

data.prod()

120.0

In [ ]:
# Para calcular la desviacion standard de todos los elementos

data.std()

1.4142135623730951

In [ ]:
# Para calcular la desviacion standard de numeros muy dispersos

a= np.array([1, 15, 60, 390, 550, 34, 7, 342, 100])
a.mean()

166.55555555555554

In [ ]:
# Podemos redondear el resultado de un valor, como la desviación estándar.

a.std().round(4)

193.4851

## <u>***8.- Más Ejercicios Creando Matrices***</u>

COmo hemos visto hasta ahora, puedes pasar listas de listas de Python para crear un array 2D (***matriz***).

In [ ]:
data=np.array([[1, 2], [3, 4], [5,6]])

data

array([[1, 2],
       [3, 4],
       [5, 6]])



---



A continuación, vamos a practicar un poco de slicing con la anterior matriz

In [ ]:
data[0, 1]

2

In [ ]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [ ]:
data[0:3, 0]

array([1, 3, 5])

In [ ]:
data[0:3, 0:2]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data.max()

6

In [ ]:
data.min()

1

In [ ]:
data.sum()

21



---



Podemos agregar los valores de una matriz a lo largo de las columnas o a los largo de las filas usando el parametro `axis`.
+   Si `axis=0` se suma a los largo de las columnas.
+   Si `axis=1` se suma a lo largo de las filas.

In [ ]:
data=np.array([[1, 2], [5, 3], [4, 6]])

data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [ ]:
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)


array([2, 5, 6])



---



Si tienes dos matrices del mismo tamaño (size) puedes sumar y multiplicar las matrices.

In [ ]:
data1= np.array([[1, 2], [3, 4]])
data2= np.array([[1, 1], [1, 1]])

data1 + data2

array([[2, 3],
       [4, 5]])

Para multiplicar matrices tenemos dos opciones:
+   podemos usar el simbolo `@`.
+   podemos usar el método `dot()`.

In [ ]:
# usamos el simbolo @

data1 @ data2

array([[3, 3],
       [7, 7]])

In [ ]:
# usamos la funcion dot

np.dot(data1, data2)

array([[3, 3],
       [7, 7]])



---



Puedes hacer estas operaciones matematicas en matrices de diferente tamaños, pero solo si una de las matrices tiene solo una columna o una fila. En este caso,  *NumPy usara la regla broadcast que vimos mas arriba*.

In [ ]:
data1=np.array([[1, 2], [3, 4], [5, 6]])
data2=np.array([1,1])

data1 + data2

array([[2, 3],
       [4, 5],
       [6, 7]])

## <u>***9.- Generar Números al Azar***</u>


El uso de la generación aleatoria de números es fundamental en la configuración de algoritmos numéricos y de machine learning. También en la inicialización aleatoria de pesos en redes neuronales artificiales.

> *La **inicialización aleatoria de pesos en redes neuronales artificiales** es un paso importante al comenzar a entrenar una red neuronal. En esencia, se refiere al proceso de asignar valores iniciales a los pesos de las conexiones entre las neuronas de la red.*
>
> *Cada conexión entre neuronas tiene un peso asociado, que determina la fuerza de la conexión. Al inicio del entrenamiento, estos pesos se establecen de manera aleatoria.*
>
> *La razón detrás de esta aleatoriedad es evitar que todas las neuronas de la red aprendan lo mismo al principio. Si todos los pesos fueran iguales desde el principio, las neuronas tendrían comportamientos similares y la red no sería capaz de aprender patrones complejos.*

Con el método `integers()` de la clase `Generator` en el módulo `random`, podemos generar enteros aleatoriamente desde el entero más bajo (`low`) (recuerda que este numero es incluido en NumPy) hasta el entero más alto (`high`) (excluido).

El método `integers()` tiene los parámetros (entre otros):
+   `low` el entero más bajo aleatorio que se generará.
+   `high` el entero más alto aleatorio que se generará (opcional).
+   `size` el tamaño de la matriz que se generará (opcional).
+   `endpoint=True` incluye el entero más alto en la generación aleatoria. Por defecto es `False` (opcional).

Más info en [Numpy](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers).

`rng` es la abreviatura de "*Random Number Generator*" en inglés.

Podemos generar un array de 2 x 14 de integers aleatorios entre 0 y 8 (incluido) con:

In [ ]:
# Primero creamos el objeto generador de numeros aleatorios

rng = np.random.default_rng()

# Luego usamos el método integers()

rng.integers(4, 11, size=(3, 8), endpoint=True)

array([[ 4,  8, 10,  4,  5,  4, 10,  9],
       [10,  9,  9,  6,  9,  8,  8,  7],
       [11,  5, 10,  7,  5,  5, 10,  7]])

## <u>***10.- Como Conseguir Valores Únicos y Contar Valores***</u>

Para conseguir los valores únicos de un array o una matriz, utilizamos el método `unique()`.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.unique.html#numpy.unique).

In [ ]:
a= np.array([11, 11, 11, 11, 11, 11, 14, 16, 16, 16, 16, 16, 16, 16])

u=np.unique(a)

u

array([11, 14, 16])

Para contar el numero de valores únicos usamos el parámetro `return_counts=True` del  método `unique()`.

Cuando usamos éste parámetro, el método `unique()` devuelve una matriz con dos arrays:
+   El primer array contiene los valores únicos del array o matriz dado.
+   El segundo array contiene los valores del número de veces que se repite cada valor único.

Si solo utilizamos una variable para contener el valor que devuelve el método `unique()` con el parámetro `return_counts=True`, obtendremos una matriz con los dos arrays.

En el snippet siguiente utilizamos dos variables para guardar cada array en una variable diferente:

In [ ]:
arr = np.array([[2, 4, 6, 2, 2, 5, 6, 6, 7],[8, 4, 4, 3, 2, 3, 2, 7, 4]])

In [ ]:
unicos, ocurren= np.unique(arr, return_counts=True)

print('Array de valores unicos:', unicos)
print('Array de ocurrencias:', ocurren)

Array de valores unicos: [2 3 4 5 6 7 8]
Array de ocurrencias [5 2 4 1 3 2 1]


## <u>***11.- Transponer y Reformar una Matriz***</u>

Transponer es pasar una matriz de 2x3 a una de 3x2. Para ello podemos usar el método `reshape()` (visto anteriormente) y el método `transpose()`.

El método `transpose()` es más sencillo de usar que `reshape()`, ya que realiza la acción de forma transparente para el usuario.

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html#numpy.transpose).

In [ ]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data.reshape(3,2)

array([[1, 2],
       [5, 3],
       [4, 6]])

In [ ]:
# Creamos un nuevo array

a=np.arange(20)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# Usamos el método reshape() para reformar el array anterior.

a=np.arange(20).reshape(5,4)

a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
#Y ahora usamos transpose()para invertir (transponer) los ejes (axis).

a.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
#tambien podemos usar la T

a.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

## <u>***12.-Darle la Vuelta a un Array***</u>

El método `flip()` conserva la forma (shape) de la matriz pero los elementos se reordenan (se voltea sobre un eje).

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.flip.html#numpy.flip).

In [ ]:
a= np.array([1, 2, 3, 4, 5, 6, 7, 8])

np.flip(a)


array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
# Para un array 2D funciona parecido (se voltean tanto el orden de los
# subarrays, como el orden de los elementos de cada subarray).

a2=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

a2


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.flip(a2)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

Si añadimos el parámetro `axis=`, volteamos la matriz o array sobre un eje en concreto:
+   `0` para las filas.
+   `1` para las columnas.

In [ ]:
# Le damos la vuelta solo a las filas

solofilas=np.flip(a2, axis=0)

solofilas

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [ ]:
# Le damos la vuelta solo a las columnas.

solocolumnas= np.flip(a2, axis=1)

solocolumnas

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

## <u>***13.-Aplanar Arrays Multidimensionales***</u>

> El método `flatten()` devuelve una copia de la matriz comprimida en una dimensión (1D). Podemos aplanar arrays de 2, 3, 4 dimensiones y nos las convierte en 1D

Más info en [Numpy](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten).

In [ ]:
x=np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

x


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## <u>***14.-El Método `numpy.linalg`***</u>

El método `linalg()` de **Numpy** ofrece una amplia gama de operaciones y calculos en algebra lineal como la resolucion de sistemas de ecuaciones lineales, calculo de la inversa de una matriz, etc.

> <u>***NOTA***</u>: *El término "coeficientes de las variables" se utiliza comúnmente en el contexto de modelos matemáticos y estadísticos, como en el ámbito de la regresión lineal. Los coeficientes de las variables son los valores que acompañan a las variables en un modelo matemático para expresar la relación entre esas variables*.

Más info en [Numpy](https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg).

In [ ]:
# Vamos a resolver un sistema de 3 ecuaciones lineales con 3 incognitas
# usando el metodo numpy.linalg.solve().

a= np.array([[2, 3, -1], [4, 1, 2], [3, -2, 1]]) # Coeficientes de las variables

b= np.array([7, 4, 10]) # Terminos independientes, detras del signo igual

# 2x + 3y - z = 7
# 4x + y + 2z = 4
# 3x -2y + z = 10

x=np.linalg.solve(a, b)

x

array([ 3.74074074, -1.7037037 , -4.62962963])

In [ ]:
a=np.array([[2, 3], [4, 1]])

b= np.array([7, 4])

#2x + 3y = 7
#4x + y = 4

x=np.linalg.solve(a, b)

x

array([0.5, 2. ])



---



La matriz inversa de una matriz cuadrada es la matriz que cumple la propiedad de que al multiplicarla por 𝐴, se obtiene la matriz identidad 𝐼.

> Imaginemos que tienes una caja mágica llamada "matriz cuadrada". Si colocas otra matriz dentro de esta caja y obtienes el resultado original, se dice que la matriz que pusiste adentro es la "matriz inversa".
>
>En términos más matemáticos, si tienes una matriz cuadrada 𝐴 y encuentras otra matriz 𝛣 de modo que al multiplicarlas obtienes la matriz identidad 𝐼, entonces 𝛣 es la matriz inversa de 𝐴. Se denota como 𝐴<sup>-1</sup>.
>
>La matriz inversa es como la "opuesta" que deshace lo que hace la matriz original. Sin embargo, no todas las matrices tienen una matriz inversa, y una condición importante es que la matriz original 𝐴 debe ser no singular (su determinante no debe ser cero).
>
>Piensa en esto como el "número inverso" en la multiplicación. Si tienes $3 \times \frac{1}{3} = 1$, el $\frac{1}{3}$ es el inverso de $3$ en multiplicación. De manera similar, la matriz inversa es el "inverso" de una matriz en la multiplicación de matrices.

In [ ]:
# Creamos una matriz
a = np.array([[1, 2], [3, 4]])

# Calcular la inversa de la matriz
a_inversa = np.linalg.inv(a)

# Mostrar la matriz original y su inversa
print("Matriz a:")
print(a)
print("\nInversa de la matriz a:")
print(a_inversa)

Matriz a:
[[1 2]
 [3 4]]

Inversa de la matriz a:
[[-2.   1. ]
 [ 1.5 -0.5]]


Para comprobar que hemos calculado bien la matriz inversa de 𝐴 vamos a multiplicar la matriz 𝐴 por la matriz inversa 𝛣 y nos tiene que dar la matriz identidad 𝐼 que es una matriz cuadrada en la que los elementos de la
diagonal son todos 1 y el resto de los elementos todos cero.
Por ejemplo: [1,0] [0, 1]

In [ ]:
a=np.array([[1, 2], [3, 4]])
ainv=np.array([[-2, 1], [1.5, -0.5]])

a @ ainv

array([[1., 0.],
       [0., 1.]])

## <u>***15.- Ejercicios de Arrays***</u>

In [ ]:
import numpy as np

In [ ]:
# Crear dos matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Realizar la suma de las matrices
C = A + B

# Realizar la multiplicación elemento a elemento de las matrices
D = A * B

# Realizar la multiplicación matricial de las matrices
E = np.dot(A, B)

# Calcular la transpuesta de una matriz
F = A.T

# Mostrar los resultados
print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nSuma de las matrices (A + B):")
print(C)
print("\nMultiplicación elemento a elemento (A * B):")
print(D)
print("\nMultiplicación matricial (A dot B):")
print(E)
print("\nTranspuesta de la matriz A:")
print(F)



Matriz A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz B:
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Suma de las matrices (A + B):
[[11 13 15]
 [17 19 21]
 [23 25 27]]

Multiplicación elemento a elemento (A * B):
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]

Multiplicación matricial (A dot B):
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]

Transpuesta de la matriz A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
matriz = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [8, 8, 9]])

matriz

array([[1, 2, 3],
       [4, 5, 6],
       [8, 8, 9]])

In [ ]:
# Nos va a dar error porque no todas las matrices tienen su inversa, las matrices
# singulares son cuadradas pero no tienen matriz inversa.

matriz_inversa = np.linalg.inv(matriz)

matriz_inversa

array([[ 1.        , -2.        ,  1.        ],
       [-4.        ,  5.        , -2.        ],
       [ 2.66666667, -2.66666667,  1.        ]])

In [ ]:
matriz @ matriz_inversa

array([[ 1.00000000e+00,  4.44089210e-16,  0.00000000e+00],
       [-8.88178420e-16,  1.00000000e+00,  0.00000000e+00],
       [-1.33226763e-15,  1.33226763e-15,  1.00000000e+00]])

Para ver si una matriz es inversa usamos la funcion `linalg.det()` de **Numpy** si nos da cero entonces la matriz es singular y no tiene inversa.

In [ ]:
matriz = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [8, 8, 9]])

det=np.linalg.det(matriz)

det

-2.9999999999999996

In [ ]:
# Un ejemplo de una matriz no singular es:

m= np.array([[2, 1, 3], [1, 0, 2], [3, 2, 1]])

inv=np.linalg.inv(m)

inv

array([[-1.33333333,  1.66666667,  0.66666667],
       [ 1.66666667, -2.33333333, -0.33333333],
       [ 0.66666667, -0.33333333, -0.33333333]])

### 15.1.- Sudoku de Índices

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15],
    [16,17,18,19,20], [21,22,23,24,25], [26,27,28,29,30]])

a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
# Calcula los indices de 11, 12, 16, 17

a[2:4, 0:2] #filas y columnas

array([[11, 12],
       [16, 17]])

In [ ]:
# Calcula los indices de 2, 8, 14, 20

a[[0,1,2,3], [1,2,3,4]] #filas y columnas

array([ 2,  8, 14, 20])

In [ ]:
# Calcula los indices de 4, 5, 24, 25, 29, 30

a[[0,4,5], 3:] #filas y columnas

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
# EJERCICIOS SIN SOLUCION

# Calcula los indices de 1, 5, 26, 30
# Calcula los indices de 5, 10, 15, 20, 25, 30
# Calcula los indices de 1, 7, 13, 19, 25
# Calcula los indices de 26, 21, 16, 11, 6, 1
# Calcula los indices de 11, 12, 13, 14, 15

# Realiza, a continuación, las soluciones de los ejercicios.

In [ ]:
b=np.arange(1,26).reshape(5,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
b[:2, :2]

array([[1, 2],
       [6, 7]])

In [ ]:
b[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [ ]:
b[[0,1,2,3,4], [0,1,2,3,4]]

array([ 1,  7, 13, 19, 25])

In [ ]:
b[[2,1,0], [4,4,4]]

array([15, 10,  5])

In [ ]:
b[[2,3,4], [2,2,2]]

array([13, 18, 23])

In [ ]:
b[[1,1,2,3,3], [1,3,2,1,3]]

array([ 7,  9, 13, 17, 19])

In [ ]:
b[[0,0,4,4],[0,4,4,0]]

array([ 1,  5, 25, 21])

In [ ]:
b[::-1, 4]

array([25, 20, 15, 10,  5])